### ISSUE TITLE
Scopes not set correctly

### ISSUE THREAD

**Issue by markspolakovs** [SocialiteProviders/Microsoft-Graph#1]
Is it possible to override the Mail.Send scope as is set by default? I don't want my users to see "Send mail as you" when they log in.

**Comment by faustbrian** [comment]
https://github.com/laravel/socialite

`return Socialite::driver('github')->scopes(['scope1', 'scope2'])->redirect();`

**Comment by markspolakovs** [comment]
With `return $this->socialite->with('graph')->scopes(['User.Read'])->redirect();`

I get the error

```
AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope openid mail.send User.ReadBasic.All,User.Read is not valid.
```

**Comment by faustbrian** [comment]
Seems like something is off with how the scopes are set. It was a user made provider and I am not using this so @markspolakovs could you maybe try to find the issue as you are already using it?

@CJEdgerton Could you take a look at this since you created the provider?

**Comment by CJEdgerton** [comment]
When I get a chance I will take an in depth look today. Right off the bat though the `$scopes` array looks weird (all scopes in one string). Sorry it's been a while since I worked on this.

**Comment by CJEdgerton** [comment]
So it looks like an incompatibility with how MS graph wants scopes and the `scopes` method. Graph requires a space separate list of scopes within a single string.

from the [docs](https://graph.microsoft.io/en-us/docs/get-started/php)
```php
Route::get('/oauth', function () {
    $provider = new \League\OAuth2\Client\Provider\GenericProvider([
        'clientId'                => '<YOUR_APPLICATION_ID>',
        'clientSecret'            => '<YOUR_PASSWORD>',
        'redirectUri'             => 'http://localhost:8000/oauth',
        'urlAuthorize'            => 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
        'urlAccessToken'          => 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
        'urlResourceOwnerDetails' => '',
        'scopes'                  => 'openid mail.send'
    ]);

    if (!$request->has('code')) {
        return redirect($provider->getAuthorizationUrl());
    }
});
```

Here's what I'm getting when using the following:
```php
return Socialize::driver('graph')->scopes(['User.Read'])->redirect();
```

> The provided value for the input parameter 'scope' is not valid. The scope openid mail.send User.ReadBasic.All,User.Read is not valid.

So it looks like `scopes` is just appending `User.Read` with a comma, which breaks on Graph's side.

I'm going to dig deeper into the scopes method and see if there is a way to accommodate this alternative scope format. For now you can set the scopes in `vendor\socialiteproviders\microsoft-graph\Provider.php`.

@faustbrian Since it seems to be arbitrary, should I just set the default scopes to an empty array and let the user handle it?

Thanks,
- Chris

**Comment by faustbrian** [comment]
You could a PR to https://github.com/SocialiteProviders/Providers where you override the following https://github.com/laravel/socialite/blob/3.0/src/Two/AbstractProvider.php#L64-L69

I guess the scope separator would need to be set to a space?

**Comment by faustbrian** [comment]
@markspolakovs Try the new `v2.0.1` release.

**Comment by markspolakovs** [comment]
@faustbrian Will do when I get home.

**Comment by markspolakovs** [comment]
@faustbrian Even with the `->scopes(['User.Read'])->redirect()` line, MSGraph still asks me for permission to:

```
Sign in as you  
Read all users' basic profiles  
Sign you in and read your profile  
Send mail as you  
```

when the "Send mail as you" line shouldn't be there.

**Comment by faustbrian** [comment]
@markspolakovs Which of these scopes `openid mail.send User.ReadBasic.All` would be required to read the profile details? Since this provider is user made and not directly from us I have no idea.

**Comment by markspolakovs** [comment]
(Sorry, meant to mention @CJEdgerton )

Since you ask, however, I believe the only one needed to read the user's basic profile is `User.Read`. `User.ReadBasic.All` allows the app to read the basic profiles of everyone in the O365 organisation. `Mail.Send` is unnecessary, as it is only used for sending email. `openid` is described as "Allows users to sign in to the app with their work or school accounts and allows the app to see basic user profile information."

**Comment by faustbrian** [comment]
Could you test the provider with the default scopes you recommend and then send a PR to https://github.com/SocialiteProviders/Providers?

**Comment by markspolakovs** [comment]
It seems like `User.Read` is sufficient. I'll send a PR.

/cc @CJEdgerton

**Comment by CJEdgerton** [comment]
Thanks @markspolakovs for updating that, and @faustbrian for fixing the scopes method. Sorry about that, originally I was just using `return Socialize::with('graph')->redirect();` so never noticed the issue.
